In [1]:
import pandas as pd

**PART A - Task 1**

In [69]:
population = pd.read_csv('/content/population.csv')
population

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [70]:
population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     25 non-null     object
 1   population  25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [71]:
population = pd.read_csv('/content/population.csv')
population.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [15]:
population.shape

(25, 2)

In [72]:
population.dtypes

country       object
population     int64
dtype: object

**TASK 2**

In [73]:
gdp = pd.read_excel('/content/gdp.xlsx')
gdp

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [74]:
gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  25 non-null     object
 1   GDP      25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [75]:
gdp.dtypes

Country    object
GDP         int64
dtype: object

In [18]:
gdp.columns

Index(['country', 'GDP'], dtype='object')

**TASK 3**

In [76]:
internet_users = pd.read_json('/content/internet_users.json')
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

**TASK 4**

In [77]:
literacy = pd.read_xml('/content/literacy_rate.xml')
literacy

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

**PART B - TASK 5**

In [78]:
population.columns

Index(['country', 'population'], dtype='object')

In [79]:
gdp.columns

Index(['Country', 'GDP'], dtype='object')

In [80]:
internet_users.columns

Index(['country', 'internet_users'], dtype='object')

In [81]:
literacy.columns

Index(['name', 'literacy_rate'], dtype='object')

In [82]:
population.dtypes

country       object
population     int64
dtype: object

In [83]:
gdp.dtypes

Country    object
GDP         int64
dtype: object

In [84]:
literacy.dtypes

name              object
literacy_rate    float64
dtype: object

In [85]:
internet_users.dtypes

country           object
internet_users     int64
dtype: object

In [86]:
population.shape[1]

2

In [87]:
gdp.shape[1]

2

In [88]:
literacy.shape[1]

2

In [89]:
internet_users.shape[1]

2

In [90]:
population.duplicated().sum()

np.int64(0)

In [91]:
gdp.duplicated().sum()

np.int64(0)

In [92]:
literacy.duplicated().sum()

np.int64(0)

In [93]:
internet_users.duplicated().sum()

np.int64(0)

In [94]:
population.isnull().sum()

country       0
population    0
dtype: int64

In [95]:
gdp.isnull().sum()

Country    0
GDP        0
dtype: int64

In [96]:
literacy.isnull().sum()

name             0
literacy_rate    0
dtype: int64

In [97]:
internet_users.isnull().sum()

country           0
internet_users    0
dtype: int64

**PART C** - **TASK 6 **

In [98]:
population.rename(columns={'country': 'country'})
population

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [99]:
internet_users.rename(columns={'country': 'country'}, inplace=True)
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [100]:
literacy.rename(columns={'name': 'country'}, inplace=True)
literacy

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [101]:
gdp.rename(columns={'Country': 'country'}, inplace=True)
gdp

           country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

**TASK 7**

In [46]:
population = pd.to_numeric(population['population'], errors='coerce')
population

0      331002651
1     1411778724
2     1380004385
3      125836021
4       83240525
5       67886011
6       65273511
7       60461826
8       38005238
9       25687041
10     212559417
11     145934462
12      51780579
13      46754778
14     128932753
15     273523615
16      34813871
17      84339067
18      59308690
19      45195774
20      17441139
21       8654622
22      10353442
23       5421241
24       5850342
Name: population, dtype: int64

In [49]:
gdp = pd.to_numeric(gdp ['GDP'], errors='coerce')
gdp

0     30500000
1     19230000
2      4187000
3      4180000
4      4744000
5      3839000
6      3211000
7      2420000
8      2250000
9      1880000
10     2330000
11     2200000
12     1800000
13     1710000
14     1810000
15     1500000
16     1100000
17     1350000
18      410000
19      640000
20     1150000
21      940000
22      650000
23      580000
24      530000
Name: GDP, dtype: int64

In [51]:
internet_users = pd.to_numeric(internet_users['internet_users'], errors='coerce')
internet_users

0      312000000
1     1080000000
2      850000000
3      118000000
4       79000000
5       66000000
6       62000000
7       56000000
8       36000000
9       24000000
10     181000000
11     125000000
12      50000000
13      44000000
14     102000000
15     212000000
16      34000000
17      69000000
18      43000000
19      41000000
20      17000000
21       8500000
22      10100000
23       5300000
24       5600000
Name: internet_users, dtype: int64

In [58]:
literacy = pd.to_numeric(literacy['literacy_rate'], errors='coerce')
literacy

0      99.0
1      97.2
2      77.7
3      99.0
4      99.0
5      99.0
6      99.0
7      99.0
8      99.0
9      99.0
10     93.2
11     99.7
12     98.8
13     98.6
14     95.4
15     96.0
16     97.3
17     96.7
18     95.0
19     99.1
20     99.0
21     99.0
22     99.0
23    100.0
24     97.5
Name: literacy_rate, dtype: float64

**TASK 8**

In [102]:
df = population.merge(gdp, on='country', how='inner')
df = df.merge(internet_users, on='country', how='inner')
df = df.merge(literacy, on='country', how='inner')

df.head()

         country  population       GDP  internet_users  literacy_rate
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

**TASK 9**

In [103]:
df['Internet Penetration (%)'] = ((df['internet_users'] / df['population']) * 100).round(2)
df['GDP Per Capita'] = (df['GDP'] / df['population']).round(2)
df.head()

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

**TASK** 10

In [104]:
import sqlite3
import pandas as pd

In [108]:
conn = sqlite3.connect('world_data.db')
df.to_sql('country_statistics', conn, if_exists='replace', index=False)
query = "SELECT * FROM country_statistics LIMIT 5;"
verified_df = pd.read_sql(query, conn)
conn.close()
verified_df

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

**TASK 11**

In [109]:
display(verified_df.head())

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

In [110]:
(verified_df.nlargest(5, 'GDP')[['country', 'GDP']])

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

In [111]:
(verified_df.nlargest(5, 'population')[['country', 'population']])

         country  population
1          China  1411778724
2          India  1380004385
0  United States   331002651
3          Japan   125836021
4        Germany    83240525

In [112]:
print(f"\n3. Average literacy rate: {verified_df['literacy_rate'].mean():.2f}%")

3. Average literacy rate: 94.38%

In [113]:
display(verified_df[verified_df['literacy_rate'] > 90][['country', 'literacy_rate']])

         country  literacy_rate
0  United States           99.0
1          China           97.2
3          Japan           99.0
4        Germany           99.0

In [114]:
display(verified_df[verified_df['Internet Penetration (%)'] > 70][['country', 'Internet Penetration (%)']])

         country  Internet Penetration (%)
0  United States                     94.26
1          China                     76.50
3          Japan                     93.77
4        Germany                     94.91

In [115]:
display(verified_df.nlargest(5, 'GDP Per Capita')[['country', 'GDP Per Capita']])

         country  GDP Per Capita
0  United States            0.09
4        Germany            0.06
3          Japan            0.03
1          China            0.01
2          India            0.00

In [116]:
print(f"\n7. Total population represented in the dataset: {verified_df['population'].sum():,}")

7. Total population represented in the dataset: 3,331,862,306

In [117]:
print(f"\n8. Average internet penetration across all countries: {verified_df['Internet Penetration (%)'].mean():.2f}%")

8. Average internet penetration across all countries: 84.21%

In [118]:
highest_internet_country = verified_df.loc[verified_df['internet_users'].idxmax(), 'country']
highest_internet_count = verified_df['internet_users'].max()
print(f"\n9. Country with the highest number of internet users: {highest_internet_country} ({highest_internet_count:,} users)")

9. Country with the highest number of internet users: China (1,080,000,000 users)

In [119]:
correlation = verified_df['literacy_rate'].corr(verified_df['Internet Penetration (%)'])
print(f"\n10. Correlation between Literacy Rate and Internet Penetration: {correlation:.4f}")

10. Correlation between Literacy Rate and Internet Penetration: 0.8937

**PART F**

In [129]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('world_data.db')

In [130]:
query= """
SELECT country, GDP
FROM country_statistics
ORDER BY GDP DESC
LIMIT 5;
"""
pd.read_sql_query(query, conn)

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

In [131]:
query_2 = """
SELECT AVG(literacy_rate) AS average_literacy_rate
FROM country_statistics;
"""
pd.read_sql_query(query_2, conn)

   average_literacy_rate
0                 97.248

In [132]:
query_3 = """
SELECT country, literacy_rate
FROM country_statistics
WHERE literacy_rate > 90;
"""
pd.read_sql_query(query_3, conn)

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            Japan           99.0
3          Germany           99.0
4   United Kingdom           99.0
5           France           99.0
6            Italy           99.0
7           Canada           99.0
8        Australia           99.0
9           Brazil           93.2
10          Russia           99.7
11     South Korea           98.8
12           Spain           98.6
13          Mexico           95.4
14       Indonesia           96.0
15    Saudi Arabia           97.3
16          Turkey           96.7
17    South Africa           95.0
18       Argentina           99.1
19     Netherlands           99.0
20     Switzerland           99.0
21          Sweden           99.0
22          Norway          100.0
23       Singapore           97.5