NumPy

**Q1**

In [1]:
import numpy as np
array = np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

In [2]:
import numpy as np
matrix = array.reshape(4,10)
print(matrix)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

In [3]:
import numpy as np
last_column = matrix[:, -1]
print(last_column)

[19 29 39 49]

**Q2**

In [4]:
import numpy as np
matrix1 = np.full((3,3), 5)
print(matrix1)

[[5 5 5]
 [5 5 5]
 [5 5 5]]

In [6]:
import numpy as np
matrix2 = np.arange(1,10).reshape(3,3)
print(matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [7]:
matrix_sum = matrix1 + matrix2
print(matrix_sum)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

In [8]:
matrix_product = matrix1 * matrix2
print(matrix_product)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

In [9]:
matrix_transpose = matrix_product.T
print(matrix_transpose)

[[ 5 20 35]
 [10 25 40]
 [15 30 45]]

**Q3**

In [14]:
import numpy as np
random_array = np.random.randint(10,101,15)
print(random_array)

[ 58  83  31  31  76  62  67  44  61  53  82  17 100  56  86]

In [15]:
import numpy as np
new_array = np.where(random_array > 50, -1, random_array)
print(new_array)

[-1 -1 31 31 -1 -1 -1 44 -1 -1 -1 17 -1 -1 -1]

In [16]:
import numpy as np
replaced_count = np.sum(new_array == -1)
print(replaced_count)

11

**Q4**

In [2]:
import numpy as np
random_matrix = np.random.rand(5,4)
print(random_matrix)

[[0.75163608 0.83877764 0.48572883 0.06847961]
 [0.19835209 0.47785477 0.3633227  0.68047715]
 [0.52917031 0.72507197 0.64396796 0.24352007]
 [0.57316502 0.31948454 0.41098389 0.70810263]
 [0.37059707 0.15418295 0.05148603 0.73321903]]

In [6]:
import numpy as np
row_sums = np.sum(random_matrix, axis=1)
max_row_idx = np.argmax(row_sums)
max_sum_row = random_matrix[max_row_idx]
print(row_sums)
print(max_row_idx)
print(max_sum_row)

[0.3774157  0.80269124 1.99757946 2.33825066 1.98596609]
3
[0.74513702 0.44866686 0.48867716 0.65576962]

In [5]:
import numpy as np
row_min = np.min(random_matrix, axis=1).reshape(-1,1)
row_max = np.max(random_matrix, axis=1).reshape(-1,1)
normalized_matrix = (random_matrix - row_min) / (row_max - row_min)
print("normalized Matrix (each row scaled between 0 and 1):")
print(normalized_matrix)

normalized Matrix (each row scaled between 0 and 1):
[[0.88687292 1.         0.54167245 0.        ]
 [0.         0.57973066 0.3421739  1.        ]
 [0.59318683 1.         0.83157786 0.        ]
 [0.6527758  0.         0.23544799 1.        ]
 [0.468088   0.15064097 0.         1.        ]]

**Q5**

In [6]:
import numpy as np
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_values = np.unique(arr)
print(unique_values)

[1 3 5 7 9]

In [7]:
import numpy as np
values, counts = np.unique(arr, return_counts=True)
duplicates = values[counts > 1]
print("Duplicate values in the array:",duplicates)

Duplicate values in the array: [1 3 5]

**Q6**

In [8]:
import numpy as np
matrix = np.arange(1,37).reshape(6,6)
print(matrix)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

In [9]:
import numpy as np
middle_submatrix = matrix[1:5, 1:5]
print("Middle submatrix:")
print(middle_submatrix)

Middle submatrix:
[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

In [10]:
import numpy as np
even_numbers = middle_submatrix[middle_submatrix % 2 == 0]
print("Even numbers in the middle submatrix:")
print(even_numbers)

Even numbers in the middle submatrix:
[ 8 10 14 16 20 22 26 28]

**Q7**

In [44]:
import numpy as np
array = np.arange(12).reshape(3,4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

In [45]:
reshaped = array.reshape(6,2)
print(reshaped)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

In [46]:
flattened = reshaped.flatten()
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

In [47]:
final_array = flattened.reshape(4,3)
print(final_array)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

**Q8**

In [48]:
import numpy as np
array = np.array([[1,2], [3,4]])
print(array)

[[1 2]
 [3 4]]

In [49]:
array = np.append(array, [[5,6]], axis=0)
print(array)

[[1 2]
 [3 4]
 [5 6]]

In [52]:
new_col = np.array([[7], [8], [9]])
array = np.append(array, new_col, axis=1)
print(array)

[[1 2 7]
 [3 4 8]
 [5 6 9]]

**Q9**

In [53]:
import numpy as np
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.array([7,8,9])
combined = np.concatenate((array1, array2, array3))
print(combined)

[1 2 3 4 5 6 7 8 9]

In [54]:
matrix = combined.reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [55]:
diagonal = np.diag(matrix)
print(diagonal)

[1 5 9]

    **Q10**

In [56]:
import numpy as np
array = np.arange(1,21)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

In [58]:
New_array = array[(array % 3 == 0) | (array % 5 == 0) ]
print(New_array)

[ 3  5  6  9 10 12 15 18 20]

In [59]:
count = New_array.size
print(count)

9

**Pandas Activities**

**Q1**

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('/content/titanic_dataset.csv')
print(data)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [4]:
data.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

**Q2**

In [5]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

**Q3**

In [8]:
data.groupby('Sex')['Survived'].mean()*100

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

**Q4**

In [12]:
data['Age'].mean()

np.float64(29.69911764705882)

In [14]:
data['Age'].median()

28.0

In [15]:
data['Age'].std()

14.526497332334044

**Q5**

In [16]:
data['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

**Q6**

In [19]:
data[(data['Sex'] == 'female') & (data ['Age'] < 18) & (data['Survived'])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
156,157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16.00,0,0,35851,7.7333,NaN,Q
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,22.0250,NaN,S
208,209,1,3,"Carr, Miss. Helen ""Ellen""",female,16.00,0,0,367231,7.7500,NaN,Q
233,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,31.3875,NaN,S
237,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,26.2500,NaN,S
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
329,330,1,1,"Hippach, Miss. Jean Gertrude",female,16.00,0,1,111361,57.9792,B18,C
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,NaN,C
389,390,1,2,"Lehmann, Miss. Bertha",female,17.00,0,0,SC 1748,12.0000,NaN,C
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
446,447,1,2,"Mellinger, Miss. Madeleine Violet",female,13.00,0,1,250644,19.5000,NaN,S
448,449,1,3,"Baclini, Miss. Marie Catherine",female,5.00,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.00,0,1,3101298,12.2875,NaN,S
504,505,1,1,"Maioni, Miss. Roberta",female,16.00,0,0,110152,86.5000,B79,S
530,531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,NaN,S
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,26.2500,NaN,S
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,F4,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
691,692,1,3,"Karun, Miss. Manca",female,4.00,0,1,349256,13.4167,NaN,C
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,33.0000,NaN,S
750,751,1,2,"Wells, Miss. Joan",female,4.00,1,1,29103,23.0000,NaN,S
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.00,0,0,364516,12.4750,NaN,S
780,781,1,3,"Ayoub, Miss. Banoura",female,13.00,0,0,2687,7.2292,NaN,C
781,782,1,1,"Dick, Mrs. Albert Adrian (Vera Gillespie)",female,17.00,1,0,17474,57.0000,B20,S
830,831,1,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.00,1,0,2659,14.4542,NaN,C
853,854,1,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.00,0,0,2667,7.2250,NaN,C

  **Q7**

In [23]:
median=data['Age'].median()
data['Age'].fillna(median)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

**Q8**

In [25]:
bins = [0, 17, 60, float('inf')]
labels = ['Child', 'Adult', 'Senior']
data['Age_Group'] = pd.cut(data['Age'], bins=bins, labels=labels)
data[['Name','Age','Age_Group']].head(10)

                                                Name   Age Age_Group
0                            Braund, Mr. Owen Harris  22.0     Adult
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0     Adult
2                             Heikkinen, Miss. Laina  26.0     Adult
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0     Adult
4                           Allen, Mr. William Henry  35.0     Adult
5                                   Moran, Mr. James   NaN       NaN
6                            McCarthy, Mr. Timothy J  54.0     Adult
7                     Palsson, Master. Gosta Leonard   2.0     Child
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0     Adult
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0     Child

**Q9**

In [31]:
data.sort_values(by='Fare', ascending = False).head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Group
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,Adult
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,Adult
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,Adult
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,Adult
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,Senior

**Q10**

In [32]:
data.groupby(['Pclass' , 'Sex']) ['Fare'].mean()

Pclass  Sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

**Q11**

In [33]:
data.rename(columns = {'Sex' : 'gender' , 'Fare' : 'ticket_fare'})

,PassengerId,Survived,Pclass,Name,gender,Age,SibSp,Parch,Ticket,ticket_fare,Cabin,Embarked,Age_Group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult

**Q12**

In [34]:
data.groupby('Pclass') ['Survived'].value_counts()

Pclass  Survived
1       1           136
        0            80
2       0            97
        1            87
3       0           372
        1           119
Name: count, dtype: int64

**Q13**

In [37]:
data.groupby(['Pclass','Sex']) ['Age'].mean()

Pclass  Sex
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: Age, dtype: float64