**Q1**

In [5]:
import numpy as np
import pandas as pd

**Q2**

In [14]:
data = pd.read_csv('/content/IMDB-Movie-Data.csv')
data

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

**Q3**

In [15]:
data.shape

(1000, 12)

In [17]:
data.head(5)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [20]:
data.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [21]:
data.dtypes

Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object

In [22]:
data.isnull().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

**Q4**

In [23]:
data.duplicated().sum()

np.int64(0)

In [25]:
data.drop_duplicates(inplace=True)

**Q5**

In [29]:
data.rename(columns={'Title': 'Movie_Title'})

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

**Q6**

In [32]:
data['Genre'].str.split(',').explode().str.strip().unique()

array(['Action', 'Adventure', 'Sci-Fi', 'Mystery', 'Horror', 'Thriller',
       'Animation', 'Comedy', 'Family', 'Fantasy', 'Drama', 'Music',
       'Biography', 'Romance', 'History', 'Crime', 'Western', 'War',
       'Musical', 'Sport'], dtype=object)

**Q7**

In [40]:
data['Genre_Count'] = data['Genre'].str.count(',')+1
data[['Movie_Title','Genre_Count']]

                 Movie_Title  Genre_Count
0    Guardians of the Galaxy            3
1                 Prometheus            3
2                      Split            2
3                       Sing            3
4              Suicide Squad            3
..                       ...          ...
995     Secret in Their Eyes            3
996          Hostel: Part II            1
997   Step Up 2: The Streets            3
998             Search Party            2
999               Nine Lives            3

[1000 rows x 2 columns]

**Q8**

In [45]:
revenue_median = data['Revenue (Millions)'].median()
data['Revenue (Millions)'].fillna(revenue_median)

metascore_median = data['Metascore'].median()
data['Metascore'].fillna(metascore_median)

data[['Revenue (Millions)', 'Metascore']].isnull().sum()

Revenue (Millions)    0
Metascore             0
dtype: int64

**Q9**

In [47]:
top_rated_movies = data.nlargest(5, 'Rating')
top_rated_movies[['Movie_Title', 'Rating']]

         Movie_Title  Rating
54   The Dark Knight     9.0
80         Inception     8.8
117           Dangal     8.8
36      Interstellar     8.6
96     Kimi no na wa     8.6

**Q10**

In [48]:
highest_revenue_movies = data.nlargest(5, 'Revenue (Millions)')
highest_revenue_movies[['Movie_Title', 'Revenue (Millions)']]

                                   Movie_Title  Revenue (Millions)
50  Star Wars: Episode VII - The Force Awakens              936.63
87                                      Avatar              760.51
85                              Jurassic World              652.18
76                                The Avengers              623.28
54                             The Dark Knight              533.32

In [49]:
lowest_revenue_movies = data.nsmallest(5, 'Revenue (Millions)')
lowest_revenue_movies[['Movie_Title', 'Revenue (Millions)']]

          Movie_Title  Revenue (Millions)
231  A Kind of Murder                0.00
27         Dead Awake                0.01
68          Wakefield                0.01
321          Lovesong                0.01
677       Love, Rosie                0.01

**Q11**

In [50]:
avg_rating_by_director = data.groupby('Director')['Rating'].mean()
avg_rating_by_director.head(10)

Director
Aamir Khan             8.5
Abdellatif Kechiche    7.8
Adam Leon              6.5
Adam McKay             7.0
Adam Shankman          6.3
Adam Wingard           5.9
Afonso Poyart          6.4
Aisling Walsh          7.8
Akan Satayev           6.3
Akiva Schaffer         6.7
Name: Rating, dtype: float64

**Q12**

In [51]:
movies_per_year = data ['Year'].value_counts()
movies_per_year.sort_index()

Year
2006     44
2007     53
2008     52
2009     51
2010     60
2011     63
2012     64
2013     91
2014     98
2015    127
2016    297
Name: count, dtype: int64

**Q13**

In [55]:
movies = data[(data["Rating"] > 8) & (data["Revenue (Millions)"] > 100)][["Movie_Title","Rating","Revenue (Millions)"]]
movies

                                      Movie_Title  Rating  Revenue (Millions)
0                         Guardians of the Galaxy     8.1              333.13
6                                      La La Land     8.3              151.06
36                                   Interstellar     8.6              187.99
50     Star Wars: Episode VII - The Force Awakens     8.1              936.63
54                                The Dark Knight     9.0              533.32
67                             Mad Max: Fury Road     8.1              153.63
74                                       Zootopia     8.1              341.26
76                                   The Avengers     8.1              623.28
77                           Inglourious Basterds     8.3              120.52
80                                      Inception     8.8              292.57
82                        The Wolf of Wall Street     8.2              116.87
83                                      Gone Girl     8.1              167.74
92                                       The Help     8.1              169.71
99                                   The Departed     8.5              132.37
114  Harry Potter and the Deathly Hallows: Part 2     8.1              380.96
124                         The Dark Knight Rises     8.5              448.13
138                                Shutter Island     8.1              127.97
144                              Django Unchained     8.4              162.80
241                                    Inside Out     8.2              356.45
427                          The Bourne Ultimatum     8.1              227.14
499                                            Up     8.3              292.98
634                                        WALL·E     8.4              223.81
645                                   Gran Torino     8.2              148.09
688                                   Toy Story 3     8.3              414.98
772                      How to Train Your Dragon     8.1              217.39

**Q14**

In [57]:
director_stats = data.groupby('Director').agg({
    'Rating': 'mean',
    'Revenue (Millions)': 'mean'
}).reset_index()

director_stats.columns = ['Director', 'Avg_Rating', 'Avg_Revenue_Millions']

director_stats = director_stats.sort_values(by='Avg_Rating', ascending=False)
director_stats.head(10)

                             Director  Avg_Rating  Avg_Revenue_Millions
465                     Nitesh Tiwari        8.80                11.150
108                 Christopher Nolan        8.68               303.018
470                   Olivier Nakache        8.60                13.180
392                    Makoto Shinkai        8.60                 4.680
194  Florian Henckel von Donnersmarck        8.50                11.280
0                          Aamir Khan        8.50                 1.200
452                      Naoko Yamada        8.40                47.985
122                   Damien Chazelle        8.40                82.075
543                    S.S. Rajamouli        8.30                 6.500
604                 Thomas Vinterberg        8.30                 0.610

**Q15**

In [58]:
year_stats = data.groupby('Year').agg(
    Movie_count = ('Movie_Title' , 'count'),
    Avg_Rating = ('Rating', 'mean')
).reset_index()

year_stats.sort_values(by='Year')

    Year  Movie_count  Avg_Rating
0   2006           44    7.125000
1   2007           53    7.133962
2   2008           52    6.784615
3   2009           51    6.960784
4   2010           60    6.826667
5   2011           63    6.838095
6   2012           64    6.925000
7   2013           91    6.812088
8   2014           98    6.837755
9   2015          127    6.602362
10  2016          297    6.436700

**Q16**

In [59]:
data['Profitability'] = data['Revenue (Millions)'] - data['Runtime (Minutes)']
top_10_profitable_movies = data.nlargest(10, 'Profitability')
top_10_profitable_movies[['Movie_Title', 'Profitability']]

                                    Movie_Title  Profitability
50   Star Wars: Episode VII - The Force Awakens         800.63
87                                       Avatar         598.51
85                               Jurassic World         528.18
76                                 The Avengers         480.28
12                                    Rogue One         399.17
119                                Finding Dory         389.29
54                              The Dark Knight         381.32
94                      Avengers: Age of Ultron         317.99
688                                 Toy Story 3         311.98
174                                      Frozen         298.74

**Q17**

In [61]:
data['Rating_Category'] = np.where(data['Rating'] < 6, 'Poor',
                          np.where(data['Rating'] < 7.5 , 'Average', 'Excellent'))
data[['Movie_Title', 'Rating', 'Rating_Category']].head(10)

               Movie_Title  Rating Rating_Category
0  Guardians of the Galaxy     8.1       Excellent
1               Prometheus     7.0         Average
2                    Split     7.3         Average
3                     Sing     7.2         Average
4            Suicide Squad     6.2         Average
5           The Great Wall     6.1         Average
6               La La Land     8.3       Excellent
7                 Mindhorn     6.4         Average
8       The Lost City of Z     7.1         Average
9               Passengers     7.0         Average

**Q18**

In [64]:
data['High_Score'] = data.apply(lambda row: row['Rating'] * 10 + row['Revenue (Millions)'], axis=1)
data[['Movie_Title' , 'High_Score']].head(10)

               Movie_Title  High_Score
0  Guardians of the Galaxy     414.130
1               Prometheus     196.460
2                    Split     211.120
3                     Sing     342.320
4            Suicide Squad     387.020
5           The Great Wall     106.130
6               La La Land     234.060
7                 Mindhorn     111.985
8       The Lost City of Z      79.010
9               Passengers     170.010